export enum RolType {
	admin = 'admin',
	user = 'user',
}
export const RolTypeText = {
	admin: 'Administrador',
	user: 'Usuario',
};

export enum Permission {
	super = 'SUPER',
	user = 'USER',
	userProfile = 'USER_PROFILE',
	userAdd = 'USER_ADD',
	userRead = 'USER_READ',
	userReadOne = 'USER_READ_ONE',
	userUpdate = 'USER_UPDATE',
	userDelete = 'USER_DELETE',
	rol = 'ROL',
	rolAdd = 'ROL_ADD',
	rolRead = 'ROL_READ',
	rolReadOne = 'ROL_READ_ONE',
	rolUpdate = 'ROL_UPDATE',
	rolDelete = 'ROL_DELETE',
	pathology = 'PATHOLOGY',
	pathologyAdd = 'PATHOLOGY_ADD',
	pathologyRead = 'PATHOLOGY_READ',
	pathologyReadOne = 'PATHOLOGY_READ_ONE',
	pathologyUpdate = 'PATHOLOGY_UPDATE',
	pathologyDelete = 'PATHOLOGY_DELETE',
	medicament = 'MEDICAMENT',
	medicamentAdd = 'MEDICAMENT_ADD',
	medicamentRead = 'MEDICAMENT_READ',
	medicamentReadOne = 'MEDICAMENT_READ_ONE',
	medicamentUpdate = 'MEDICAMENT_UPDATE',
	medicamentDelete = 'MEDICAMENT_DELETE',
	medicationRequest = 'MEDICATIONREQUEST',
	medicationRequestAdd = 'MEDICATIONREQUEST_ADD',
	medicationRequestRead = 'MEDICATIONREQUEST_READ',
	medicationRequestReadOne = 'MEDICATIONREQUEST_READ_ONE',
	medicationRequestUpdate = 'MEDICATIONREQUEST_UPDATE',
	medicationRequestDelete = 'MEDICATIONREQUEST_DELETE',
	pharmacy = 'PHARMACY',
	pharmacyAdd = 'PHARMACY_ADD',
	pharmacyRead = 'PHARMACY_READ',
	pharmacyReadOne = 'PHARMACY_READ_ONE',
	pharmacyUpdate = 'PHARMACY_UPDATE',
	pharmacyDelete = 'PHARMACY_DELETE',
	patients = 'PATIENTS',
	patientsAdd = 'PATIENTS_ADD',
	patientsRead = 'PATIENTS_READ',
	patientsReadOne = 'PATIENTS_READ_ONE',
	patientsUpdate = 'PATIENTS_UPDATE',
	patientsDelete = 'PATIENTS_DELETE',
	logRead = 'LOG_READ',
}

export const permissionTranslations = {
	SUPER: 'Super Usuario',
	USER: 'Usuario',
	USER_PROFILE: 'Perfil de Usuario',
	USER_ADD: 'Agregar Usuario',
	USER_READ: 'Leer Usuario',
	USER_READ_ONE: 'Leer Un Usuario',
	USER_UPDATE: 'Actualizar Usuario',
	USER_DELETE: 'Eliminar Usuario',
	ROL: 'Rol',
	ROL_ADD: 'Agregar Rol',
	ROL_READ: 'Leer Rol',
	ROL_READ_ONE: 'Leer Un Rol',
	ROL_UPDATE: 'Actualizar Rol',
	ROL_DELETE: 'Eliminar Rol',
	PATHOLOGY: 'Patología',
	PATHOLOGY_ADD: 'Agregar Patología',
	PATHOLOGY_READ: 'Leer Patología',
	PATHOLOGY_READ_ONE: 'Leer Una Patología',
	PATHOLOGY_UPDATE: 'Actualizar Patología',
	PATHOLOGY_DELETE: 'Eliminar Patología',
	MEDICAMENT: 'Medicamento',
	MEDICAMENT_ADD: 'Agregar Medicamento',
	MEDICAMENT_READ: 'Leer Medicamento',
	MEDICAMENT_READ_ONE: 'Leer Un Medicamento',
	MEDICAMENT_UPDATE: 'Actualizar Medicamento',
	MEDICAMENT_DELETE: 'Eliminar Medicamento',
	MEDICATIONREQUEST: 'Solicitud de Medicación',
	MEDICATIONREQUEST_ADD: 'Agregar Solicitud de Medicación',
	MEDICATIONREQUEST_READ: 'Leer Solicitud de Medicación',
	MEDICATIONREQUEST_READ_ONE: 'Leer Una Solicitud de Medicación',
	MEDICATIONREQUEST_UPDATE: 'Actualizar Solicitud de Medicación',
	MEDICATIONREQUEST_DELETE: 'Eliminar Solicitud de Medicación',
	PHARMACY: 'Farmacia',
	PHARMACY_ADD: 'Agregar Farmacia',
	PHARMACY_READ: 'Leer Farmacia',
	PHARMACY_READ_ONE: 'Leer Una Farmacia',
	PHARMACY_UPDATE: 'Actualizar Farmacia',
	PHARMACY_DELETE: 'Eliminar Farmacia',
	PATIENTS: 'Pacientes',
	PATIENTS_ADD: 'Agregar Paciente',
	PATIENTS_READ: 'Leer Paciente',
	PATIENTS_READ_ONE: 'Leer Un Paciente',
	PATIENTS_UPDATE: 'Actualizar Paciente',
	PATIENTS_DELETE: 'Eliminar Paciente',
	LOG_READ: 'Leer Registro',
};
